#!/bin/sh

PATH="${PATH}:."

if [ -f "$(user-union -P)/usr/bin/hello" ]
then
  echo "Error - there is a /usr/bin/hello file, that interferes with tests"
  exit 1
fi

echo Hello > /usr/bin/hello

# This particular disaster can happen on Cygwin - stop early.
if [ -f "$(user-union -P)/usr/bin/hello" ]
then
  echo "FAILURE TO INVOKE user-union, AND it is allowing /usr/bin writes"
  exit 1
fi

cp /usr/bin/hello /usr/bin/hello2

mkdir /usr/share10
cd /usr
mkdir /usr/share11
echo Hello again > /dev/null

cd bin
ln -s mkdir mkdir_symlink
ln -s /bin/mkdir mkdir_symlink2
ln -s /tmp/redir/usr/bin/hello slink_usr_bin_hello

ln hello2 hello3

touch /usr/bin/bigbad
rm /usr/bin/bigbad

echo "We will move this" > /usr/bin/starterfile
mv /usr/bin/starterfile /usr/bin/starterfile2

pwd > current_directory

